// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Runtime serverless can use a pooled URL; migrations should prefer the
    // provider's direct connection when DIRECT_URL is available.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
