import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import { PageHeader } from "@/components/layout/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { StatusBadge } from "@/components/data/status-badge";
import { formatDate } from "@/lib/utils";
export const dynamic = "force-dynamic";
export default async function ContactDetail({ params }: { params: Promise<{ id: string }> }) { const { userId } = await requireUser(); const contact = await prisma.contact.findFirst({ where: { id: (await params).id, userId }, include: { consentAuditLogs: { orderBy: { createdAt: "desc" } }, messages: { orderBy: { createdAt: "desc" }, take: 20 }, listMemberships: { include: { list: true } } } }); if (!contact) notFound(); return <><PageHeader eyebrow="Contato" title={contact.name} description={contact.phone} /><div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Perfil e elegibilidade</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><Row label="E-mail" value={contact.email || "—"} /><Row label="Empresa" value={contact.company || "—"} /><Row label="Telefone" value={<StatusBadge status={contact.phoneStatus} />} /><Row label="Consentimento" value={<StatusBadge status={contact.consentStatus} />} /><Row label="Opt-out" value={contact.optOut ? "Sim" : "Não"} /><Row label="Listas" value={contact.listMemberships.map((item) => item.list.name).join(", ") || "—"} /></CardContent></Card><Card><CardHeader><CardTitle>Auditoria de consentimento</CardTitle></CardHeader><CardContent className="space-y-3">{contact.consentAuditLogs.length ? contact.consentAuditLogs.map((entry) => <div key={entry.id} className="rounded-xl border p-3 text-sm"><div className="flex justify-between"><StatusBadge status={entry.newStatus} /><span className="text-xs text-[var(--muted)]">{formatDate(entry.createdAt)}</span></div><p className="mt-2 text-[var(--muted)]">Fonte: {entry.source}</p></div>) : <p className="text-sm text-[var(--muted)]">Nenhuma evidência registrada.</p>}</CardContent></Card></div></>; }
function Row({ label, value }: { label: string; value: React.ReactNode }) { return <div className="flex items-center justify-between gap-4 border-b py-2 last:border-0"><span className="text-[var(--muted)]">{label}</span><span className="text-right font-medium">{value}</span></div>; }
