"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input, Label } from "@/components/ui/input";

type Template = { id: string; name: string; language: string; category: string; variables: unknown };
export function CampaignForm({ lists, templates }: { lists: Array<{ id: string; name: string }>; templates: Template[] }) {
  const [step, setStep] = useState(1); const [name, setName] = useState(""); const [listId, setListId] = useState(""); const [templateId, setTemplateId] = useState(""); const [mapping, setMapping] = useState<Record<string, string>>({}); const [scheduledAt, setScheduledAt] = useState(""); const [loading, setLoading] = useState(false); const router = useRouter(); const template = templates.find((item) => item.id === templateId); const variables = Array.isArray(template?.variables) ? template.variables.map(String) : [];
  async function create() { setLoading(true); const response = await fetch("/api/campaigns", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, listId, templateId, language: template?.language, variableMapping: mapping, scheduledAt: scheduledAt ? new Date(scheduledAt).toISOString() : undefined, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone }) }); const data = await response.json(); setLoading(false); if (!response.ok) return toast.error(data.error || "Falha ao criar campanha"); toast.success("Campanha criada"); router.push(`/campaigns/${data.id}`); router.refresh(); }
  return <Card><CardHeader><CardTitle>Etapa {step} de 5</CardTitle><CardDescription>{["Identificação", "Público", "Template aprovado", "Variáveis", "Revisão e agendamento"][step - 1]}</CardDescription></CardHeader><CardContent className="space-y-5">
    {step === 1 && <div><Label>Nome da campanha</Label><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Campanha Setembro" /></div>}
    {step === 2 && <div><Label>Lista</Label><select className="h-11 w-full rounded-xl border bg-[var(--surface)] px-3" value={listId} onChange={(e) => setListId(e.target.value)}><option value="">Selecione</option>{lists.map((list) => <option key={list.id} value={list.id}>{list.name}</option>)}</select></div>}
    {step === 3 && <div><Label>Template</Label><select className="h-11 w-full rounded-xl border bg-[var(--surface)] px-3" value={templateId} onChange={(e) => { setTemplateId(e.target.value); setMapping({}); }}><option value="">Selecione</option>{templates.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.language} · {item.category}</option>)}</select></div>}
    {step === 4 && <div className="space-y-3">{variables.length ? variables.map((variable) => <div key={variable} className="grid gap-2 sm:grid-cols-[100px_1fr] sm:items-center"><b>{`{{${variable}}}`}</b><select className="h-11 rounded-xl border bg-[var(--surface)] px-3" value={mapping[variable] || ""} onChange={(e) => setMapping({ ...mapping, [variable]: e.target.value })}><option value="">Selecione o campo</option><option value="name">Nome</option><option value="email">E-mail</option><option value="company">Empresa</option><option value="custom.cidade">Cidade</option><option value="custom.produto">Produto</option><option value="custom.valor">Valor</option></select></div>) : <p className="text-sm text-[var(--muted)]">Este template não possui variáveis de corpo.</p>}</div>}
    {step === 5 && <div className="space-y-4"><div className="rounded-xl bg-[var(--surface-muted)] p-4 text-sm"><p><b>Campanha:</b> {name}</p><p><b>Lista:</b> {lists.find((item) => item.id === listId)?.name}</p><p><b>Template:</b> {template?.name} ({template?.language})</p></div><div><Label>Agendar (opcional)</Label><Input type="datetime-local" value={scheduledAt} onChange={(e) => setScheduledAt(e.target.value)} /></div><p className="text-sm text-[var(--muted)]">A criação não envia mensagens. A elegibilidade será calculada quando você iniciar a campanha.</p></div>}
    <div className="flex justify-between"><Button variant="secondary" disabled={step === 1} onClick={() => setStep(step - 1)}>Voltar</Button>{step < 5 ? <Button disabled={(step === 1 && !name) || (step === 2 && !listId) || (step === 3 && !templateId) || (step === 4 && variables.some((key) => !mapping[key]))} onClick={() => setStep(step + 1)}>Continuar</Button> : <Button disabled={loading} onClick={create}>{loading ? "Criando…" : "Criar campanha"}</Button>}</div>
  </CardContent></Card>;
}
