"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { Check, ChevronRight, FileSpreadsheet, Upload } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Label } from "@/components/ui/input";
import { Table, TBody, TD, TH, THead } from "@/components/ui/table";
import { StatusBadge } from "@/components/data/status-badge";

type Preview = { rawDelimiter: string; delimiter: string; headers: string[]; hasHeader: boolean; mapping: Record<string, string>; total: number; valid: number; duplicates: number; invalid: number; preview: Array<{ sourceRow: number; name: string; phone: string | null; email?: string; phoneStatus: string; consentStatus: string; error?: string }> };

const destinations = ["ignore", "name", "phone", "email", "company", "consent", "optInAt", "optInSource"];

export function ImportWizard({ lists }: { lists: Array<{ id: string; name: string }> }) {
  const [step, setStep] = useState(1); const [fileName, setFileName] = useState(""); const [content, setContent] = useState(""); const [delimiter, setDelimiter] = useState<string>(""); const [preview, setPreview] = useState<Preview | null>(null); const [mapping, setMapping] = useState<Record<string, string>>({}); const [listId, setListId] = useState(""); const [loading, setLoading] = useState(false); const [result, setResult] = useState<Record<string, number> | null>(null);
  const steps = ["Upload", "Detecção", "Mapeamento", "Prévia", "Validação", "Resultado"];
  const phoneMapped = useMemo(() => Object.values(mapping).includes("phone"), [mapping]);
  async function analyze(nextMapping?: Record<string, string>) {
    setLoading(true); const response = await fetch("/api/contacts/import/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content, delimiter: delimiter || undefined, mapping: nextMapping }) }); const data = await response.json(); setLoading(false); if (!response.ok) return toast.error(data.error || "Falha ao analisar arquivo"); setPreview(data); setDelimiter(data.rawDelimiter); setMapping(data.mapping); return data as Preview;
  }
  async function commit() { setLoading(true); const response = await fetch("/api/contacts/import/commit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fileName, content, delimiter, mapping, listId: listId || undefined }) }); const data = await response.json(); setLoading(false); if (!response.ok) return toast.error(data.error || "Falha na importação"); setResult(data); setStep(6); toast.success("Importação concluída"); }
  return <div><div className="mb-6 grid grid-cols-3 gap-2 sm:grid-cols-6">{steps.map((label, index) => <div key={label} className={`rounded-xl border px-3 py-2 text-xs font-semibold ${step === index + 1 ? "border-[var(--primary)] bg-[var(--primary-soft)] text-[var(--primary-strong)]" : step > index + 1 ? "bg-[var(--surface-muted)]" : "text-[var(--muted)]"}`}><span className="mr-1">{step > index + 1 ? <Check className="inline h-3 w-3" /> : index + 1}.</span>{label}</div>)}</div>
  <Card><CardHeader><CardTitle>{steps[step - 1]}</CardTitle><CardDescription>{step === 1 ? "CSV ou TXT com até 10 MB. A coluna opt_in é opcional." : "Revise os dados antes de gravar contatos."}</CardDescription></CardHeader><CardContent>
  {step === 1 && <div className="space-y-5"><label className="grid min-h-56 cursor-pointer place-items-center rounded-2xl border border-dashed bg-[var(--surface-muted)] p-8 text-center"><div><Upload className="mx-auto mb-3 h-8 w-8 text-[var(--primary)]" /><p className="font-semibold">Selecione um arquivo CSV ou TXT</p><p className="mt-1 text-sm text-[var(--muted)]">Separadores detectados: vírgula, ponto e vírgula, pipe ou TAB</p></div><input className="sr-only" type="file" accept=".csv,.txt,text/csv,text/plain" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 10_000_000) return toast.error("Arquivo maior que 10 MB"); setFileName(file.name); setContent(await file.text()); }} /></label>{fileName && <p className="flex items-center gap-2 text-sm"><FileSpreadsheet className="h-4 w-4 text-[var(--primary)]" />{fileName}</p>}<Button disabled={!content || loading} onClick={async () => { const data = await analyze(); if (data) setStep(2); }}>Analisar arquivo <ChevronRight className="h-4 w-4" /></Button></div>}
  {step === 2 && preview && <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Info label="Registros" value={preview.total} /><Info label="Colunas" value={preview.headers.length} /><Info label="Separador" value={preview.delimiter} /></div><div><Label>Separador</Label><select className="h-11 rounded-xl border bg-[var(--surface)] px-3" value={delimiter} onChange={(e) => setDelimiter(e.target.value)}><option value=",">Vírgula</option><option value=";">Ponto e vírgula</option><option value="|">Pipe</option><option value={"\t"}>TAB</option></select></div><div className="flex gap-2"><Button variant="secondary" onClick={() => setStep(1)}>Voltar</Button><Button onClick={async () => { const data = await analyze(); if (data) setStep(3); }}>Continuar</Button></div></div>}
  {step === 3 && preview && <div className="space-y-4"><p className="text-sm text-[var(--muted)]">Mapeie as colunas da sua lista. Campos desconhecidos são preservados como personalizados.</p>{preview.headers.map((header) => <div key={header} className="grid gap-2 rounded-xl border p-3 sm:grid-cols-2 sm:items-center"><span className="font-medium">{header}</span><select className="h-10 rounded-lg border bg-[var(--surface)] px-3" value={mapping[header] || "ignore"} onChange={(event) => setMapping({ ...mapping, [header]: event.target.value })}>{destinations.map((destination) => <option key={destination} value={destination}>{destination}</option>)}<option value={`custom.${header.toLowerCase().replace(/\W+/g, "_")}`}>Campo personalizado</option></select></div>)}{!phoneMapped && <p className="text-sm text-[var(--danger)]">Mapeie uma coluna para Telefone.</p>}<div className="flex gap-2"><Button variant="secondary" onClick={() => setStep(2)}>Voltar</Button><Button disabled={!phoneMapped} onClick={async () => { const data = await analyze(mapping); if (data) setStep(4); }}>Gerar prévia</Button></div></div>}
  {step === 4 && preview && <div className="space-y-4"><Table><THead><tr><TH>Nome</TH><TH>Telefone</TH><TH>E-mail</TH><TH>Consentimento</TH><TH>Resultado</TH></tr></THead><TBody>{preview.preview.map((row) => <tr key={row.sourceRow}><TD>{row.name}</TD><TD>{row.phone || "INVALID_PHONE"}</TD><TD>{row.email || "—"}</TD><TD><StatusBadge status={row.consentStatus} /></TD><TD>{row.error ? <span className="text-[var(--danger)]">{row.error}</span> : <span className="text-[var(--primary)]">Válido</span>}</TD></tr>)}</TBody></Table><div className="flex gap-2"><Button variant="secondary" onClick={() => setStep(3)}>Voltar</Button><Button onClick={() => setStep(5)}>Validar lote</Button></div></div>}
  {step === 5 && preview && <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-4"><Info label="Total" value={preview.total} /><Info label="Válidos" value={preview.valid} /><Info label="Duplicados" value={preview.duplicates} /><Info label="Inválidos" value={preview.invalid} /></div><div><Label>Adicionar à lista (opcional)</Label><select className="h-11 w-full max-w-md rounded-xl border bg-[var(--surface)] px-3" value={listId} onChange={(e) => setListId(e.target.value)}><option value="">Nenhuma lista</option>{lists.map((list) => <option key={list.id} value={list.id}>{list.name}</option>)}</select></div><p className="rounded-xl bg-[var(--primary-soft)] p-4 text-sm text-[var(--primary-strong)]"><b>Importar ≠ autorizar.</b> Contatos sem consentimento permanecem UNKNOWN e não entram em campanhas de marketing.</p><div className="flex gap-2"><Button variant="secondary" onClick={() => setStep(4)}>Voltar</Button><Button disabled={loading} onClick={commit}>{loading ? "Importando…" : "Confirmar importação"}</Button></div></div>}
  {step === 6 && result && <div className="py-6 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[var(--primary-soft)] text-[var(--primary-strong)]"><Check /></span><h3 className="mt-4 text-xl font-bold">Importação concluída</h3><p className="mt-1 text-[var(--muted)]">{result.totalRows?.toLocaleString("pt-BR")} registros processados</p><div className="mx-auto mt-5 grid max-w-xl gap-3 sm:grid-cols-4"><Info label="Importados" value={result.importedRows} /><Info label="Duplicados" value={result.duplicateRows} /><Info label="Inválidos" value={result.invalidRows} /><Info label="Existentes" value={result.existingRows} /></div><Button className="mt-6" asChild><Link href="/contacts">Ver contatos</Link></Button></div>}
  </CardContent></Card></div>;
}

function Info({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border bg-[var(--surface-muted)] p-3"><p className="text-xs text-[var(--muted)]">{label}</p><p className="mt-1 text-lg font-bold">{typeof value === "number" ? value.toLocaleString("pt-BR") : value}</p></div>; }
