"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function CreateListForm() { const [name, setName] = useState(""); const router = useRouter(); return <form className="flex gap-2" onSubmit={async (e) => { e.preventDefault(); const response = await fetch("/api/lists", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); if (!response.ok) return toast.error("Não foi possível criar a lista"); setName(""); toast.success("Lista criada"); router.refresh(); }}><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Nome da lista" required /><Button>Criar</Button></form>; }
export function AddAllContactsButton({ listId }: { listId: string }) { const router = useRouter(); const [loading, setLoading] = useState(false); return <Button variant="secondary" className="w-full" disabled={loading} onClick={async () => { setLoading(true); const response = await fetch(`/api/lists/${listId}/members/all`, { method: "POST", headers: { "Content-Type": "application/json" } }); const data = await response.json(); setLoading(false); if (!response.ok) return toast.error(data.error || "Falha ao adicionar contatos"); toast.success(data.added ? `${data.added} contatos adicionados` : "Todos os contatos já estavam na lista"); router.refresh(); }}>{loading ? "Adicionando…" : "Adicionar todos os contatos"}</Button>; }
export function SyncTemplatesButton() { const router = useRouter(); const [loading, setLoading] = useState(false); return <Button disabled={loading} onClick={async () => { setLoading(true); const response = await fetch("/api/templates/sync", { method: "POST" }); const data = await response.json(); setLoading(false); if (!response.ok) return toast.error(data.error || "Falha na sincronização"); toast.success(`${data.synced} templates sincronizados`); router.refresh(); }}>{loading ? "Sincronizando…" : "Sincronizar templates"}</Button>; }
export function AddSuppressionForm() { const [phone, setPhone] = useState(""); const [reason, setReason] = useState(""); const router = useRouter(); return <form className="grid gap-2 sm:grid-cols-[1fr_2fr_auto]" onSubmit={async (e) => { e.preventDefault(); const response = await fetch("/api/suppression", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ phone, reason }) }); const data = await response.json(); if (!response.ok) return toast.error(data.error || "Falha"); setPhone(""); setReason(""); toast.success("Número suprimido"); router.refresh(); }}><Input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="Telefone" required /><Input value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Motivo" required /><Button>Adicionar</Button></form>; }
