"use client";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input, Label } from "@/components/ui/input";
import { StatusBadge } from "@/components/data/status-badge";

type Account = { wabaId?: string; phoneNumberId?: string; apiVersion?: string; displayPhoneNumber?: string | null; businessName?: string | null; hasAccessToken?: boolean; hasAppSecret?: boolean; hasWebhookVerifyToken?: boolean; status?: string } | null;
export function WhatsAppSettingsForm({ account, mode }: { account: Account; mode: string }) {
  const [testing, setTesting] = useState(false); const [result, setResult] = useState<Record<string, boolean> | null>(null);
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form.entries()); for (const secret of ["accessToken", "appSecret", "webhookVerifyToken"]) if (!payload[secret]) delete payload[secret]; const response = await fetch("/api/settings/whatsapp", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) return toast.error(data.error || "Falha ao salvar"); toast.success("Configuração salva com os segredos cifrados"); }
  async function test() { setTesting(true); const response = await fetch("/api/settings/whatsapp/test", { method: "POST" }); const data = await response.json(); setTesting(false); if (!response.ok) return toast.error(data.action || data.error || "Falha na conexão"); setResult(data); toast.success(mode === "mock" ? "Mock conectado (não é a Meta real)" : "WhatsApp conectado"); }
  return <form className="space-y-5" onSubmit={save}><div className="flex items-center gap-2"><StatusBadge status={account?.status || "DISCONNECTED"} />{mode === "mock" && <StatusBadge status="MOCK" />}</div><div className="grid gap-4 sm:grid-cols-2"><Field label="WABA ID" name="wabaId" defaultValue={account?.wabaId || (mode === "mock" ? "mock-waba" : "")} /><Field label="Phone Number ID" name="phoneNumberId" defaultValue={account?.phoneNumberId || (mode === "mock" ? "mock-phone" : "")} /><Field label="API Version" name="apiVersion" defaultValue={account?.apiVersion || "v25.0"} /><Field label="Display Phone Number" name="displayPhoneNumber" defaultValue={account?.displayPhoneNumber || ""} /><Field label="Business Name" name="businessName" defaultValue={account?.businessName || ""} /><SecretField label="Access Token" name="accessToken" stored={account?.hasAccessToken} placeholder="Cole o token permanente da Meta" /><SecretField label="App Secret" name="appSecret" stored={account?.hasAppSecret} placeholder="Cole o App Secret da Meta" /><SecretField label="Webhook Verify Token" name="webhookVerifyToken" stored={account?.hasWebhookVerifyToken} placeholder="Crie uma string aleatória com 16+ caracteres" /></div><p className="text-xs text-[var(--muted)]">Use o Webhook Verify Token informado aqui também no painel da Meta. Todos os segredos são cifrados no backend.</p><div className="flex gap-2"><Button type="submit">Salvar configuração</Button><Button type="button" variant="secondary" disabled={testing} onClick={test}>{testing ? "Testando…" : "Testar conexão"}</Button></div>{result && <div className="grid gap-2 rounded-xl bg-[var(--surface-muted)] p-4 sm:grid-cols-2">{[["WhatsApp conectado", result.connected], ["WABA encontrada", result.wabaFound], ["Número encontrado", result.phoneFound], ["API acessível", result.apiAccessible]].map(([label, ok]) => <p key={String(label)} className={ok ? "text-[var(--primary-strong)]" : "text-[var(--danger)]"}>✓ {label}</p>)}</div>}</form>;
}
function Field({ label, name, defaultValue }: { label: string; name: string; defaultValue: string }) { return <div><Label htmlFor={name}>{label}</Label><Input id={name} name={name} defaultValue={defaultValue} required={["wabaId", "phoneNumberId", "apiVersion"].includes(name)} /></div>; }
function SecretField({ label, name, stored, placeholder }: { label: string; name: string; stored?: boolean; placeholder: string }) { return <div><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type="password" placeholder={stored ? "Já armazenado — deixe vazio para manter" : placeholder} autoComplete="off" /></div>; }
